export const COLORS = {
  brand:          '#0d3580',
  brandHover:     '#1a4ba0',
  brandActive:    '#2458b8',
  brandTint:      '#e8edf8',
  brandBorder:    '#c8d3ee',
  pageBg:         '#F7F8FA',
  cardBg:         '#FFFFFF',
  inputBg:        '#F0F2F7',
  separator:      '#e2e4ea',
  textPrimary:    '#111111',
  textSecondary:  '#3d3d3d',
  textMuted:      '#6b7280',
  textPlaceholder:'#9ca3af',
  success:        '#16a34a',
  successBg:      '#dcfce7',
  danger:         '#dc2626',
  dangerBg:       '#fee2e2',
  warning:        '#d97706',
  warningBg:      '#fef9c3',
  info:           '#1d4ed8',
  infoBg:         '#dbeafe',
  orange:         '#c2410c',
  orangeBg:       '#ffedd5',
}

export const TYPOGRAPHY = {
  titleCard:    { fontSize: '17px', fontWeight: '600', color: '#111111', lineHeight: '1.3' },
  titleSection: { fontSize: '15px', fontWeight: '600', color: '#111111' },
  subtitleCard: { fontSize: '13px', fontWeight: '500', color: '#111111' },
  body:         { fontSize: '14px', fontWeight: '400', color: '#111111' },
  caption:      { fontSize: '12px', fontWeight: '400', color: '#6b7280' },
  label:        { fontSize: '11px', fontWeight: '600', color: '#6b7280', letterSpacing: '0.06em', textTransform: 'uppercase' },
  metric:       { fontSize: '22px', fontWeight: '600', color: '#0d3580' },
}

export const COMPONENTS = {
  card: {
    background:   '#FFFFFF',
    borderRadius: '14px',
    border:       '1.5px solid #0d3580',
    padding:      '18px 20px',
  },
  cardMetric: {
    background:   '#FFFFFF',
    borderRadius: '10px',
    border:       '1.5px solid #0d3580',
    padding:      '12px 16px',
  },
  btnPrimary: {
    background:   '#0d3580',
    color:        '#FFFFFF',
    border:       'none',
    borderRadius: '8px',
    padding:      '9px 20px',
    fontSize:     '13px',
    fontWeight:   '500',
    cursor:       'pointer',
  },
  btnSecondary: {
    background:   'transparent',
    color:        '#0d3580',
    border:       '1.5px solid #0d3580',
    borderRadius: '8px',
    padding:      '8px 20px',
    fontSize:     '13px',
    fontWeight:   '500',
    cursor:       'pointer',
  },
  btnGhost: {
    background:   'transparent',
    color:        '#111111',
    border:       '1.5px solid #e2e4ea',
    borderRadius: '8px',
    padding:      '8px 20px',
    fontSize:     '13px',
    fontWeight:   '400',
    cursor:       'pointer',
  },
  input: {
    background:   '#F0F2F7',
    border:       '1.5px solid transparent',
    borderRadius: '8px',
    padding:      '9px 12px',
    fontSize:     '14px',
    color:        '#111111',
  },
  sidebar: {
    background:   '#0d3580',
    width:        '220px',
    itemActive:   { background: 'rgba(255,255,255,0.15)', color: '#ffffff', fontWeight: '500' },
    itemDefault:  { color: 'rgba(255,255,255,0.6)' },
  },
}

export const BADGES = {
  brouillon:      { background: '#f3f4f6', color: '#374151' },
  envoyee:        { background: '#dbeafe', color: '#1d4ed8' },
  payee:          { background: '#dcfce7', color: '#16a34a' },
  annulee:        { background: '#fee2e2', color: '#dc2626' },
  en_attente:     { background: '#fef9c3', color: '#a16207' },
  en_retard:      { background: '#ffedd5', color: '#c2410c' },
  en_cours:       { background: '#dcfce7', color: '#16a34a' },
  accepte:        { background: '#e8edf8', color: '#0d3580' },
  refuse:         { background: '#fee2e2', color: '#dc2626' },
  expire:         { background: '#f3f4f6', color: '#6b7280' },
  termine:        { background: '#e8edf8', color: '#0d3580' },
  valide:         { background: '#dcfce7', color: '#16a34a' },
  en_maintenance: { background: '#fef9c3', color: '#a16207' },
  a_verifier:     { background: '#fef9c3', color: '#a16207' },
  rejete:         { background: '#fee2e2', color: '#dc2626' },
  paye:           { background: '#dcfce7', color: '#16a34a' },
  synced:         { background: '#dcfce7', color: '#16a34a' },
  pending:        { background: '#ffedd5', color: '#c2410c' },
  archivee:       { background: '#f3f4f6', color: '#6b7280' },
  archive:        { background: '#f3f4f6', color: '#6b7280' },
}
